[package]
name = "jgd-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
rusqlite = "0.32.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
tower = "0.5.1"
